import type { Metadata } from "next";
import "./globals.css";
import { FloatingNavDemo } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Sumit Singh | My portfolio website",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-black overflow-x-hidden">
        <FloatingNavDemo />
        {children}
      </body>
    </html>
  );
}
