name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main
      - master
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-push-docker:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker Login Status
        run: |
          echo "Docker Hub login successful, proceeding with build and push"
          docker info

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.portfolio
          push: true
          tags: sumitsabarwal5/portfolio:latest
          cache-from: type=registry,ref=sumitsabarwal5/portfolio:buildcache
          cache-to: type=registry,ref=sumitsabarwal5/portfolio:buildcache,mode=max

      - name: Verify Pushed Image
        run: |
          echo "Image pushed to Docker Hub: sumitsabarwal5/portfolio:latest"
          echo "Check it at https://hub.docker.com/r/sumitsabarwal5/portfolio"

      - name: Deployment Status
        run: |
          echo "Deployment workflow completed"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
